# Generated by Django 4.2.1 on 2023-06-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
    ]
