# Generated by Django 4.2.1 on 2023-06-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_exp_product_life_product_mfd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='This is a short product des', null=True),
        ),
    ]
