# Generated by Django 4.2.1 on 2023-06-25 08:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is a category', null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is a sub category', null=True),
        ),
    ]
