# Generated by Django 4.2.1 on 2023-08-27 11:49

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ord', unique=True),
        ),
    ]
