# Generated by Django 4.2.1 on 2023-08-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
