# Generated by Django 4.2.1 on 2023-08-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_address_contact_no_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_no',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
